package com.hibernate.pojo;
// Generated Mar 27, 2015 4:38:21 PM by Hibernate Tools 4.3.1


import com.hibernate.pojo.User;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="Message" ,catalog="Chat_DB")
public class Message  implements java.io.Serializable {


    private Integer id;
    private User user;
    private String message;
    private Date time;

    public Message() {
    }


    public Message(User user, Date time) {
        this.user = user;
        this.time = time;
    }
    public Message(User user, String message, Date time) {
        this.user = user;
        this.message = message;
        this.time = time;
    }

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user", nullable=false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }


    @Column(name="message", length=45)
    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time", nullable=false, length=19)
    public Date getTime() {
        return this.time;
    }

    public void setTime(Date time) {
        this.time = time;
    }






}


