package com.hibernate.pojo;
// Generated Mar 27, 2015 2:25:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "Message", catalog = "Chat_DB")
public class Message implements java.io.Serializable {


    private Integer id;
    private User userByToUser;
    private User userByFromUser;
    private String message;
    private Date time;

    public Message() {
    }


    public Message(User userByToUser, User userByFromUser, Date time) {
        this.userByToUser = userByToUser;
        this.userByFromUser = userByFromUser;
        this.time = time;
    }

    public Message(User userByToUser, User userByFromUser, String message, Date time) {
        this.userByToUser = userByToUser;
        this.userByFromUser = userByFromUser;
        this.message = message;
        this.time = time;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "toUser", nullable = false)
    public User getUserByToUser() {
        return this.userByToUser;
    }

    public void setUserByToUser(User userByToUser) {
        this.userByToUser = userByToUser;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fromUser", nullable = false)
    public User getUserByFromUser() {
        return this.userByFromUser;
    }

    public void setUserByFromUser(User userByFromUser) {
        this.userByFromUser = userByFromUser;
    }


    @Column(name = "message", length = 45)
    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "time", nullable = false, length = 19)
    public Date getTime() {
        return this.time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

}


