package com.hibernate.pojo;
// Generated Mar 27, 2015 4:38:21 PM by Hibernate Tools 4.3.1


import com.hibernate.pojo.Message;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="User"
        ,catalog="Chat_DB"
)
public class User  implements java.io.Serializable {


    private Integer id;
    private String fullName;
    private String email;
    private String password;
    private Set<Message> messages = new HashSet<Message>(0);

    public User() {
    }


    public User(String email, String password) {
        this.email = email;
        this.password = password;
    }
    public User(String fullName, String email, String password, Set<Message> messages) {
        this.fullName = fullName;
        this.email = email;
        this.password = password;
        this.messages = messages;
    }

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @Column(name="fullName", length=500)
    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }


    @Column(name="email", nullable=false, length=500)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="password", nullable=false, length=500)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Message> getMessages() {
        return this.messages;
    }

    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }




}


